config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  resources :users
  resources :password_resets
  resources :furnitures
  post "/furniture/search" => "furnitures#index"
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get "/auth/google_oauth2/callback" => "users#google_oauth2"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authenticate.rb
class Authenticate < ApplicationRecord
end

app/models/furniture.rb
class Furniture < ApplicationRecord
	belongs_to :user, required: false

  	#mount_uploader :image, AvatarUploader

 	scope :item, -> (input_item) { where("item ILIKE ?", "%#{input_item}%") }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :furnitures 
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  before_create {generate_token(:auth_token)}

  mount_uploader :image, ImageUploader

  def user?
      self.type == "User"
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    # save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  	def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
        user = User.create(
           email: data['email'],
           password: SecureRandom.hex
        )
    end
    user
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

  def current_user
    # @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController

	def index
		@furniture = Furniture.all
		@search = Furniture.where(nil)
		filtering_params(params).each do |key, value|
			@search = @search.public_send(key, value) if value.present?	
		end

		respond_to do |format| 
			format.html
			format.js 
		end 
	end

	def create
		@furniture = current_user.furnitures.new(furniture_params)
		if @furniture.save
			redirect_to root_path
		else
			redirect_to new_furniture_path
		end

	end

	def new
		@furniture = Furniture.new
	end


	def show
	end

	def edit
		@furniture = current_user.furnitures.find(params[:id])
	end
	
	def update
		@furniture = Furniture.find(params[:id])
		@furniture.update_attributes(furniture_params)
		redirect_to root_path
	end

    def destroy
    	@furniture = Furniture.delete(params[:id])
    	@number = params[:id]
    	redirect_to root_path
    end

 #    def search
 #    	@search = Furniture.where(nil)
	# 	filtering_params(params).each do |key, value|
	# 	@search = @search.public_send(key, value) if value.present?	
	# 	end

	# 	respond_to do |format| 
	# 		format.html
	# 		format.js 
	# 	end 
	# end

	private
	 def find_furniture
      @furniture = Furniture.find(params[:id])
    end

    def furniture_params
      params.require(:furniture).permit(:item, :category, :description, {image:[]})
    end

    def filtering_params(params)
    	params.slice(:item , :category)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
    respond_to do |format|
      format.html { render :layout => 'welcome' }
    end
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  	def new
	end

	  def create
	  	user = User.find_by_email(params[:email])
	  	user.send_password_reset if user
	  	redirect_to root_path, :notice => "Email send with password reset"
	  end

	  def edit
	  	@user = User.find_by_password_reset_token!(params[:password_reset_token])
	  end

	  def update
	  	@user = User.find_by_password_reset_token!(params[:password_reset_token])
	  	if @user.password_reset_sent_at <=> 2.hours.ago
	  		redirect_to new_password_reset_path , :alert =>"Password reset has expired."
	  	elsif @user.update_attributes(user_params)
	  		redirect_to root_path, :notice => "Password has been reset!"
	  	else
	  		redirect_to edit_password_reset_path
	  end
	end

	def show
	end
end

private
	def user_params
    	params.require(:user).permit(:password_digest,:password, :password_confirmation)
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.where(email: params[:email]).first
	  	if user && user.authenticate(params[:password])
		    session[:user_id] = user.id # important to only store userid in cookie(session) and not other information of the user to not have too big a cookie and risk "cookie overflow".
		    flash[:notice] = "Welcome, you've logged in."
		    redirect_to root_path
	  else
	    	flash[:error] = "There is something wrong with your username or password."
	    	redirect_to login_path
  end
end


	def edit
	end

	def destroy
	  session[:user_id] = nil
	  flash[:notice] = "You've logged out."
	  redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save 
			session[:user_id] = @user.id # to automatically login a user that signed up
    		flash[:notice] = "You are registered."
			redirect_to root_url
		else
			flash[:notice] = "Invalid email or password"
			redirect_to new_user_path
		end
	end

def google_oauth2
     @user = User.from_omniauth(request.env['omniauth.auth'])          
     session[:user_id] = @user.id                                       
     redirect_to root_path                                        
 end

private
def user_params
  params.require(:user).permit(:email,:password_confirmation ,:password,:password_digest, :_destroy)
end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furniture_helper.rb
module FurnitureHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/furnitures/_partial.html.erb
<% @search.each do |p| %>
<h1><%= p.item %></h1>
<h4><%= p.description %></h4>
<%= p.category %>
<% end %>

app/views/furnitures/edit.html.erb
Edit your model
<%= form_for @furniture do |f| %>
<div class="furniture_field">
<%= f.label :item %>
<%= f.text_field :item %>
</div>

<div class="furniture_field">
<%= f.label :description %>
<%= f.text_field :description %>
</div>

<div class="furniture_field">
<%= f.label :category %>
<%= f.select(:category, [ 'Big', 'Small', 'Medium' ], {}, { :class => 'select' }) %></div>

<div class="furniture_field">
<%= f.file_field :image %>
<%= f.submit 'Upload' %>
</div>

<% end %>

app/views/furnitures/index.html.erb
	<div id="search">
		<%= form_tag furnitures_path,method: :get , remote: true do %>
			<%= text_field_tag :item,params[:item] %>
			<%= submit_tag 'Search' %>
		<%end%>
	</div>
	<div id="searchitem">
	</div>
	<div id="alllist">
	<% @furniture.each do |f| %>
		<%#= f.image %>
		<h1><%= f.item %></h1>
		<h4><%= f.description %></h4>
		<%= f.category %>
		<%if current_user == f.user%>
        <p> <%=link_to "edit", edit_furniture_path(f)%></p>
        <% end %>
		<br>______________________________<br>
	<% end %>
	</div>
	<%= link_to 'Upload Your Furniture', new_furniture_path %>

app/views/furnitures/index.js.erb
$("#alllist").html("");
$("#searchitem").html("");
$('#searchitem').append('<%= escape_javascript (render(partial: 'partial')) %>');

app/views/furnitures/new.html.erb
<%= form_for @furniture do |f| %>

<div class="furniture_field">
<%= f.label :item %>
<%= f.text_field :item %>
</div>

<div class="furniture_field">
<%= f.label :description %>
<%= f.text_field :description %>
</div>

<div class="furniture_field">
<%= f.label :category %>
<%= f.text_field :category %>
</div>

<div class="furniture_field">
<%= f.file_field :image %>
<%= f.submit 'Upload' %>
</div>

<% end %>

app/views/home/index.html.erb
    <iframe class ="map"
 height="250px"
 frameborder="0" style="border:0"
 src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBX8hQcoSEtucwisPltvD2u0Xsl7nZg77I
   &q=<%= h("IDA Academy").gsub(/(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)\s?(\S*)/, '\1+\2+\3+\4+\5+\6+\7+\8')%>&q=seattle+washington&q=arizona" allowfullscreen>
</iframe>

<div class="homeIndex"> Interior Archictecture Design</div>

<%= link_to 'Get your model',furnitures_path , :class => "myButton"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IDA</title>
    <%= csrf_meta_tags %>
     <link rel="icon" type="image/jpg" href="icon.jpg">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
  </head>

  <body>
   
<nav class="navbar navbar-default " id="navigation" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <%= link_to 'IDA Academy', root_path %>

        </div> 
           <form class="form-inline my-2 my-lg-0" style="float: right;">
      <% if current_user %>
        Signed in as <%= current_user.email %> | <%= link_to "Logout", '/logout' %>

      <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', new_user_path %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
      <% end %>
    </form>
    </div>
  </nav> 

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

    <%= yield %>
  </body>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/layouts/welcome.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks' => true %>
   <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   </head>

<body>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%=image_tag("home1.jpg", :class => "d-block w-100", :alt => "IDA")%>
        <div class="carousel-caption">
        <h3>IDA</h3>
        <p>Interior Archictecture Design</p>
      </div>
      </div>

      <div class="item">
        <%=image_tag("home2.jpg", :class => "d-block w-100", :alt => "IDA")%>
         <div class="carousel-caption">
        <h3>IDA</h3>
        <p>Interior Archictecture Design</p>
      </div>
      </div>
    
      <div class="item">
        <%=image_tag("home3.jpg", :class => "d-block w-100", :alt => "IDA")%>
         <div class="carousel-caption">
        <h3>IDA</h3>
        <p>Interior Archictecture Design</p>
      </div>
      </div>


<a class="left carousel-control" href="#myCarousel" data-slide="prev">
<span class="glyphicon glyphicon-chevron-left"></span> 
</a>
<a class="right carousel-control" href="#myCarousel" data-slide="next">
<span class="glyphicon glyphicon-chevron-right"></span> 
</a>
</div>
</div>

<nav class="navbar navbar-default " id="navigation" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <%= link_to 'IDA Academy', root_path %>
        </div> 
           <form class="form-inline my-2 my-lg-0" style="float: right;">
      <% if current_user %>
        Signed in as <%= current_user.email %> | <%= link_to "Logout", '/logout' %>
      <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', new_user_path %>
        <%= link_to "|Sign in with Google", "/auth/google_oauth2" %>
      <% end %>
    </form>
    </div>
  </nav>

<div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

    <%= yield %>
</body>

app/views/password_resets/edit.html.erb
Password Reset

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
<% if @user.errors.any? %>
	<div class="errorMessage">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user .errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<%= f.submit "Reset Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset your password</h1>
<%= form_tag password_resets_url do %>
	<%= label_tag :email %>
	<%= text_field_tag :email,params[:email] %>
	<%= submit_tag "Reset Password" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |n| %>

<div id="sign_field">
	<%= n.label :email %>
	<%= n.text_field :email %>
</div>

<div id="sign_field">
	<%= n.label :password %>
	<%= n.password_field :password %>
</div>

<div id="sign_field">
	<%= n.label :password_confirmation %>
	<%= n.password_field :password_confirmation %>
</div>
<%= n.submit "sign up"%>

<% end %>